namespace BinGuiDev;

public static class DevContext{
    public static readonly List<string> Symbols =[
        "ETHUSDT",
        "BTCUSDT",
        "SOLUSDT",
        "XRPUSDT",
        "BNBUSDT",
        "ERAUSDT",
        "SUIUSDT",
        "FDUSDUSDT",
        "DOGEUSDT",
        "ENAUSDT",
        "PENGUUSDT",
        "PEPEUSDT",
        "BONKUSDT",
        "OPUSDT",
        "ADAUSDT",
        "TRXUSDT",
        "CAKEUSDT",
        "HBARUSDT",
        "BCHUSDT",
        "AVAXUSDT",
        "ASRUSDT",
        "WIFUSDT",
        "CRVUSDT",
        "UNIUSDT",
        "LINKUSDT",
        "LTCUSDT",
        "ATMUSDT",
        "ALTUSDT",
        "ARBUSDT",
        "WLDUSDT",
        "USD1USDT",
        "SEIUSDT",
        "TRUMPUSDT",
        "AAVEUSDT",
        "XLMUSDT",
        "FLOKIUSDT",
        "MAVUSDT",
        "SPKUSDT",
        "FETUSDT",
        "NEARUSDT",
        "KNCUSDT",
        "OMNIUSDT",
        "RESOLVUSDT",
        "TAOUSDT",
        "ONDOUSDT",
        "JUPUSDT",
        "APTUSDT",
        "ETHFIUSDT",
        "CFXUSDT",
        "PNUTUSDT",
        "NEIROUSDT",
        "SYRUPUSDT",
        "HYPERUSDT",
        "LDOUSDT",
        "ENSUSDT",
        "DOTUSDT",
        "JUVUSDT",
        "1000CATUSDT",
        "ORDIUSDT",
        "HAEDALUSDT",
        "RAYUSDT",
        "CETUSUSDT",
        "CUSDT",
        "SUSDT",
        "SHIBUSDT",
        "TONUSDT",
        "SANTOSUSDT",
        "VIRTUALUSDT",
        "TIAUSDT",
        "ACMUSDT",
        "GLMUSDT",
        "EURUSDT",
        "PENDLEUSDT",
        "INJUSDT",
        "ETCUSDT",
        "THEUSDT",
        "RUNEUSDT",
        "EIGENUSDT",
        "REZUSDT",
        "WCTUSDT",
        "ALGOUSDT",
        "ICPUSDT",
        "GALAUSDT",
        "HFTUSDT",
        "OMUSDT",
        "XUSDUSDT",
        "CITYUSDT",
        "PAXGUSDT",
        "OGUSDT",
        "PSGUSDT",
        "CVXUSDT",
        "BERAUSDT",
        "MKRUSDT",
        "INITUSDT",
        "LISTAUSDT",
        "POLUSDT",
        "BARUSDT",
        "RENDERUSDT"
    ];
    
    public static readonly Dictionary<string, long> GraphPeriodDb = new Dictionary<string, long>(){
        {"1s", 1},
        {"1m", 60},
        {"5m", 300},
        {"15m", 900},
        {"1h", 3600},
        {"4h", 14400},
        {"1d", 86400}
    };
}